skimrish: added new Integers
mwiski/Skirmish pull request #1
Opened 2019-04-05 21:22 UTC by mwiski

2019-04-05 21:28 UTC, mwiski commented
Wypuściłem to na początku na masterze, a potem stworzyłem branch skirmish1 i zacząłem się zastanawiać, czy nie powinienem tego zostawić na masterze, a poprawić dopiero, gdy dasz mi znać co poprawić. Czy mógłbym wypushować program na branchu bez komendy git push origin master?

Zadanie zrobiłem poprzez przefiltrowanie listy przez HashSet, aczkolwiek nie takie było moje pierwotne zamierzenie. Początkowo zrobiłem coś takiego, ale miałem nieprawidłowy wynik po kompilacji
![image](https://user-images.githubusercontent.com/49036916/55657361-4013f100-57fa-11e9-9f9e-220a444e5f2e.png)

Nie wiem, czy zdjęcie będzie dostępne, więc wrzucę je do rozmowy na Hangouts też,

2019-04-06 11:22 UTC, mps4dev commented
Od początku robisz zadanie na branczu dedykowanym, a dopiero po akceptacji merdżujesz do mastera :) Po gdyby się zdarzyło, że masz jakieś błędy, to po gdybyś od razu robił na masterze i wypuszował, to wszyscy by mogli sobie ściągnąć wersję mastera z błędami. 
Nie da się wypuszować bez git push, ale git push origin master - takiego czegoś nie robimy!!!! git push origin feature-branch (git push --set-upstream origin feature-branch), a do mastera dopiero puszujemy po zmerdżowaniu :D Najlepiej merdżować tutaj w githubie.

2019-04-06 11:23 UTC, mps4dev commented on src/main/java/pl/mwiski/skirmishes/SkirmishOne.java
> +        ints.add(6);
Przez to, że wcześniej coś zrobiłeś i wypuszowałeś, to teraz w pull requeście widzę tylko te trzy zmienione linijki i niczego więcej :P

2019-04-06 11:27 UTC, mps4dev requested changes
:-1: 
metoda init() nie powinna się znajdować w klasie Skirmish, ale w SkirmishApplication.
Twoje rozwiązanie niszczy kolejność wrzuconych elementów - HashSet to taka kolekcja, w której nie ma duplikatów, ale też nie jest zachowana kolejność dodawania do niej elementów.  Jest taka implementacja interfejsu Set, która spełnia oba założenia i tu ją można zastosować. Docelowo nasze rozwiązanie powinno się składać z jednej linijki, w której są tylko wywoływane konstruktory :)

2019-04-09 14:09 UTC, merged